### ISSUE TITLE
Topic-awareness

### ISSUE THREAD

**Issue by mcleod-ic** [586837r/node-red-contrib-ring-buffer#1]
Hi, what would it take to make this Topic-aware?

Can I apply Topics to it externally somehow?  or can I conly get one buffer per node?

**Comment by 586837r** [comment]
This node ignored the topic before. Now (v0.10.0) you can enable *Separate Buffer per Topic* in the settings!

**Comment by mcleod-ic** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  That's great to hear.  Thanks!                                                                                                                                                                        Sent from my BlackBerry — the most secure mobile device                                                                                                                                                                           From: notifications@github.comSent: 18 June 2019 11:34 pmTo: node-red-contrib-ring-buffer@noreply.github.comReply to: reply@reply.github.comCc: paul.mcleod@inspiredchoice.biz; author@noreply.github.comSubject: Re: [586837r/node-red-contrib-ring-buffer] Topic-awareness (#1)  This node ignored the topic before. Now (v0.10.0) you can enable Separate Buffer per Topic in the settings!

**Comment by mcleod-ic** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Wow that's truly amazing responsiveness, and makes a huge difference. Thank you!Regards,Paul                                                                                                                                                                                                                                                                                                                From: paul.mcleod@inspiredchoice.bizSent: 19 June 2019 1:15 amTo: reply@reply.github.com; node-red-contrib-ring-buffer@noreply.github.comCc: author@noreply.github.comSubject: Re: [586837r/node-red-contrib-ring-buffer] Topic-awareness (#1)  #ssc15184 #response_container_BBPPID{font-family: initial;font-size: initial;color: initial;}  That's great to hear.  Thanks!                                                                                                                                                                        Sent from my BlackBerry — the most secure mobile device                                                                                                                                                                           From:  notifications@github.comSent: 18 June 2019 11:34 pmTo:  node-red-contrib-ring-buffer@noreply.github.comReply to:  reply@reply.github.comCc:  paul.mcleod@inspiredchoice.biz; author@noreply.github.comSubject: Re: [586837r/node-red-contrib-ring-buffer] Topic-awareness (#1)  This node ignored the topic before. Now (v0.10.0) you can enable Separate Buffer per Topic in the settings!

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
